# Generated by Django 4.1.5 on 2023-02-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_todo_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='checker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.CharField(max_length=50)),
            ],
        ),
    ]
