# Generated by Django 4.1.5 on 2023-02-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_checker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checker',
            name='box',
            field=models.BooleanField(default=False),
        ),
    ]
