# Generated by Django 4.1.5 on 2023-02-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_checker_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checker',
            name='box',
            field=models.BooleanField(),
        ),
    ]
